# DataGerry - OpenSource Enterprise CMDB
# Copyright (C) 2026 becon GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
"""
Implementation of Importer API routes helper methods
"""
import os
import tempfile
from typing import Any
from logging import Logger, getLogger
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from cmdb.manager.query_builder import BuilderParameters
from cmdb.manager import TypesManager

from cmdb.framework.importer.helper.importer_helper import load_parser_class
from cmdb.models.user_model import CmdbUser
from cmdb.models.type_model import CmdbType
from cmdb.security.acl.permission import AccessControlPermission
from cmdb.interface.rest_api.routes.importer_routes.importer_constants import IMPORTER_KIND_OBJECT

from cmdb.errors.security import AccessDeniedError
# -------------------------------------------------------------------------------------------------------------------- #

LOGGER: Logger = getLogger(__name__)

# -------------------------------------------------------------------------------------------------------------------- #

def generate_parsed_output(request_file: FileStorage, file_format: str, parser_config: dict) -> Any:
    """
    Save an uploaded file to a temporary file and parse its content using a format-specific parser

    The upload is written to a per-request temporary file (removed again afterwards) so that
    concurrent parses of the same filename cannot clobber each other's data.

    Args:
        request_file (FileStorage): The uploaded file to parse
        file_format (str): The format of the file (e.g., 'json', 'csv') used to select the parser
        parser_config (dict): Configuration settings passed to the parser

    Returns:
        Any: The parsed output generated by the parser
    """
    # Load parser class
    parser_class = load_parser_class(IMPORTER_KIND_OBJECT, file_format)

    # Save the upload to a private temporary file
    suffix = f'_{secure_filename(request_file.filename)}'
    file_descriptor, working_file = tempfile.mkstemp(suffix=suffix)
    os.close(file_descriptor)

    try:
        request_file.save(working_file)

        # parse content
        parser = parser_class(parser_config)

        return parser.parse(working_file)
    finally:
        if os.path.exists(working_file):
            os.remove(working_file)


def verify_import_access(user: CmdbUser, _type: CmdbType, types_manager: TypesManager) -> None:
    """
    Ensures the user's group may import (read/create/update) objects of the given type

    The type passes if it has no active ACL, or if the user's group is granted READ + CREATE + UPDATE
    on it. A type with an active ACL that does not grant the group all three is treated as protected.

    Args:
        user (CmdbUser): The user requesting the import (its group id is checked against the ACL)
        _type (CmdbType): The type the objects are imported into
        types_manager (TypesManager): Manager used to re-query the type under the ACL filter

    Raises:
        AccessDeniedError: If the type's ACL does not grant the user's group import access
    """
    location = 'acl.groups.includes.' + str(user.group_id)
    query = {'$and': [
        {'$or': [
            {'acl': {'$exists': False}},
            {'acl.activated': False},
            {'$and': [
                {'acl.activated': True},
                {location: {'$exists': True}},
                {location: {'$all': [
                    AccessControlPermission.READ.value,
                    AccessControlPermission.CREATE.value,
                    AccessControlPermission.UPDATE.value,
                ]}},
            ]},
        ]},
        {'public_id': _type.public_id},
    ]}

    builder_params = BuilderParameters(criteria=query, limit=1)
    types_ = types_manager.iterate(builder_params)

    if types_.total == 0:
        raise AccessDeniedError(f'The objects of the type `{_type.name}` are protected by ACL permission!')
