/*
* DATAGERRY - OpenSource Enterprise CMDB
* Copyright (C) 2019 NETHINKS GmbH
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.

* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import { Component, Injectable, Input, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, Validators } from '@angular/forms';
import { TypeService } from '../../../../services/type.service';
import { CategoryService } from '../../../../services/category.service';
import { CmdbCategory } from '../../../../models/cmdb-category';
import { Observable } from 'rxjs';
import { CmdbMode } from '../../../../modes.enum';


@Injectable()
export class TypeNameValidator {

  static createValidator(typeService: TypeService) {
    return (control: AbstractControl) => {
      return typeService.validateTypeName(control.value).then(res => {
        return res ? null : {nameAlreadyTaken: true};
      });
    };
  }
}

@Component({
  selector: 'cmdb-type-basic-step',
  templateUrl: './type-basic-step.component.html',
  styleUrls: ['./type-basic-step.component.scss'],
  providers: [TypeNameValidator]
})
export class TypeBasicStepComponent implements OnInit {

  @Input()
  set preData(data: any) {
    if (data !== undefined) {
      this.basicForm.patchValue(data);
      this.basicMetaIconForm.patchValue(data.render_meta === undefined ? 'fa-cube' : data.render_meta);
    }
  }

  @Input() public mode: CmdbMode;
  public modes = CmdbMode;

  public basicForm: FormGroup;
  public basicMetaIconForm: FormGroup;
  public basicCategoryForm: FormGroup;
  public categoryList: Observable<CmdbCategory[]>;
  public icons = [
    'glass',
    'music',
    'search',
    'envelope-o',
    'heart',
    'star',
    'star-o',
    'user',
    'film',
    'th-large',
    'th',
    'th-list',
    'check',
    'times',
    'search-plus',
    'search-minus',
    'power-off',
    'signal',
    'cog',
    'trash-o',
    'home',
    'file-o',
    'clock-o',
    'road',
    'download',
    'arrow-circle-o-down',
    'arrow-circle-o-up',
    'inbox',
    'play-circle-o',
    'repeat',
    'refresh',
    'list-alt',
    'lock',
    'flag',
    'headphones',
    'volume-off',
    'volume-down',
    'volume-up',
    'qrcode',
    'barcode',
    'tag',
    'tags',
    'book',
    'bookmark',
    'print',
    'camera',
    'font',
    'bold',
    'italic',
    'text-height',
    'text-width',
    'align-left',
    'align-center',
    'align-right',
    'align-justify',
    'list',
    'outdent',
    'indent',
    'video-camera',
    'picture-o',
    'pencil',
    'map-marker',
    'adjust',
    'tint',
    'pencil-square-o',
    'share-square-o',
    'check-square-o',
    'arrows',
    'step-backward',
    'fast-backward',
    'backward',
    'play',
    'pause',
    'stop',
    'forward',
    'fast-forward',
    'step-forward',
    'eject',
    'chevron-left',
    'chevron-right',
    'plus-circle',
    'minus-circle',
    'times-circle',
    'check-circle',
    'question-circle',
    'info-circle',
    'crosshairs',
    'times-circle-o',
    'check-circle-o',
    'ban',
    'arrow-left',
    'arrow-right',
    'arrow-up',
    'arrow-down',
    'share',
    'expand',
    'compress',
    'plus',
    'minus',
    'asterisk',
    'exclamation-circle',
    'gift',
    'leaf',
    'fire',
    'eye',
    'eye-slash',
    'exclamation-triangle',
    'plane',
    'calendar',
    'random',
    'comment',
    'magnet',
    'chevron-up',
    'chevron-down',
    'retweet',
    'shopping-cart',
    'folder',
    'folder-open',
    'arrows-v',
    'arrows-h',
    'bar-chart',
    'twitter-square',
    'facebook-square',
    'camera-retro',
    'key',
    'cogs',
    'comments',
    'thumbs-o-up',
    'thumbs-o-down',
    'star-half',
    'heart-o',
    'sign-out',
    'linkedin-square',
    'thumb-tack',
    'external-link',
    'sign-in',
    'trophy',
    'github-square',
    'upload',
    'lemon-o',
    'phone',
    'square-o',
    'bookmark-o',
    'phone-square',
    'twitter',
    'facebook',
    'github',
    'unlock',
    'credit-card',
    'rss',
    'hdd-o',
    'bullhorn',
    'bell',
    'certificate',
    'hand-o-right',
    'hand-o-left',
    'hand-o-up',
    'hand-o-down',
    'arrow-circle-left',
    'arrow-circle-right',
    'arrow-circle-up',
    'arrow-circle-down',
    'globe',
    'wrench',
    'tasks',
    'filter',
    'briefcase',
    'arrows-alt',
    'users',
    'link',
    'cloud',
    'flask',
    'scissors',
    'files-o',
    'paperclip',
    'floppy-o',
    'square',
    'bars',
    'list-ul',
    'list-ol',
    'strikethrough',
    'underline',
    'table',
    'magic',
    'truck',
    'pinterest',
    'pinterest-square',
    'google-plus-square',
    'google-plus',
    'money',
    'caret-down',
    'caret-up',
    'caret-left',
    'caret-right',
    'columns',
    'sort',
    'sort-desc',
    'sort-asc',
    'envelope',
    'linkedin',
    'undo',
    'gavel',
    'tachometer',
    'comment-o',
    'comments-o',
    'bolt',
    'sitemap',
    'umbrella',
    'clipboard',
    'lightbulb-o',
    'exchange',
    'cloud-download',
    'cloud-upload',
    'user-md',
    'stethoscope',
    'suitcase',
    'bell-o',
    'coffee',
    'cutlery',
    'file-text-o',
    'building-o',
    'hospital-o',
    'ambulance',
    'medkit',
    'fighter-jet',
    'beer',
    'h-square',
    'plus-square',
    'angle-double-left',
    'angle-double-right',
    'angle-double-up',
    'angle-double-down',
    'angle-left',
    'angle-right',
    'angle-up',
    'angle-down',
    'desktop',
    'laptop',
    'tablet',
    'mobile',
    'circle-o',
    'quote-left',
    'quote-right',
    'spinner',
    'circle',
    'reply',
    'github-alt',
    'folder-o',
    'folder-open-o',
    'smile-o',
    'frown-o',
    'meh-o',
    'gamepad',
    'keyboard-o',
    'flag-o',
    'flag-checkered',
    'terminal',
    'code',
    'reply-all',
    'star-half-o',
    'location-arrow',
    'crop',
    'code-fork',
    'chain-broken',
    'question',
    'info',
    'exclamation',
    'superscript',
    'subscript',
    'eraser',
    'puzzle-piece',
    'microphone',
    'microphone-slash',
    'shield',
    'calendar-o',
    'fire-extinguisher',
    'rocket',
    'maxcdn',
    'chevron-circle-left',
    'chevron-circle-right',
    'chevron-circle-up',
    'chevron-circle-down',
    'html5',
    'css3',
    'anchor',
    'unlock-alt',
    'bullseye',
    'ellipsis-h',
    'ellipsis-v',
    'rss-square',
    'play-circle',
    'ticket',
    'minus-square',
    'minus-square-o',
    'level-up',
    'level-down',
    'check-square',
    'pencil-square',
    'external-link-square',
    'share-square',
    'compass',
    'caret-square-o-down',
    'caret-square-o-up',
    'caret-square-o-right',
    'eur',
    'gbp',
    'usd',
    'inr',
    'jpy',
    'rub',
    'krw',
    'btc',
    'file',
    'file-text',
    'sort-alpha-asc',
    'sort-alpha-desc',
    'sort-amount-asc',
    'sort-amount-desc',
    'sort-numeric-asc',
    'sort-numeric-desc',
    'thumbs-up',
    'thumbs-down',
    'youtube-square',
    'youtube',
    'xing',
    'xing-square',
    'youtube-play',
    'dropbox',
    'stack-overflow',
    'instagram',
    'flickr',
    'adn',
    'bitbucket',
    'bitbucket-square',
    'tumblr',
    'tumblr-square',
    'long-arrow-down',
    'long-arrow-up',
    'long-arrow-left',
    'long-arrow-right',
    'apple',
    'windows',
    'android',
    'linux',
    'dribbble',
    'skype',
    'foursquare',
    'trello',
    'female',
    'male',
    'gratipay',
    'sun-o',
    'moon-o',
    'archive',
    'bug',
    'vk',
    'weibo',
    'renren',
    'pagelines',
    'stack-exchange',
    'arrow-circle-o-right',
    'arrow-circle-o-left',
    'caret-square-o-left',
    'dot-circle-o',
    'wheelchair',
    'vimeo-square',
    'try',
    'plus-square-o',
    'space-shuttle',
    'slack',
    'envelope-square',
    'wordpress',
    'openid',
    'university',
    'graduation-cap',
    'yahoo',
    'google',
    'reddit',
    'reddit-square',
    'stumbleupon-circle',
    'stumbleupon',
    'delicious',
    'digg',
    'pied-piper',
    'pied-piper-alt',
    'drupal',
    'joomla',
    'language',
    'fax',
    'building',
    'child',
    'paw',
    'spoon',
    'cube',
    'cubes',
    'behance',
    'behance-square',
    'steam',
    'steam-square',
    'recycle',
    'car',
    'taxi',
    'tree',
    'spotify',
    'deviantart',
    'soundcloud',
    'database',
    'file-pdf-o',
    'file-word-o',
    'file-excel-o',
    'file-powerpoint-o',
    'file-image-o',
    'file-archive-o',
    'file-audio-o',
    'file-video-o',
    'file-code-o',
    'vine',
    'codepen',
    'jsfiddle',
    'life-ring',
    'circle-o-notch',
    'rebel',
    'empire',
    'git-square',
    'git',
    'hacker-news',
    'tencent-weibo',
    'qq',
    'weixin',
    'paper-plane',
    'paper-plane-o',
    'history',
    'circle-thin',
    'header',
    'paragraph',
    'sliders',
    'share-alt',
    'share-alt-square',
    'bomb',
    'futbol-o',
    'tty',
    'binoculars',
    'plug',
    'slideshare',
    'twitch',
    'yelp',
    'newspaper-o',
    'wifi',
    'calculator',
    'paypal',
    'google-wallet',
    'cc-visa',
    'cc-mastercard',
    'cc-discover',
    'cc-amex',
    'cc-paypal',
    'cc-stripe',
    'bell-slash',
    'bell-slash-o',
    'trash',
    'copyright',
    'at',
    'eyedropper',
    'paint-brush',
    'birthday-cake',
    'area-chart',
    'pie-chart',
    'line-chart',
    'lastfm',
    'lastfm-square',
    'toggle-off',
    'toggle-on',
    'bicycle',
    'bus',
    'ioxhost',
    'angellist',
    'cc',
    'ils',
    'meanpath',
    'buysellads',
    'connectdevelop',
    'dashcube',
    'forumbee',
    'leanpub',
    'sellsy',
    'shirtsinbulk',
    'simplybuilt',
    'skyatlas',
    'cart-plus',
    'cart-arrow-down',
    'diamond',
    'ship',
    'user-secret',
    'motorcycle',
    'street-view',
    'heartbeat',
    'venus',
    'mars',
    'mercury',
    'transgender',
    'transgender-alt',
    'venus-double',
    'mars-double',
    'venus-mars',
    'mars-stroke',
    'mars-stroke-v',
    'mars-stroke-h',
    'neuter',
    'genderless',
    'facebook-official',
    'pinterest-p',
    'whatsapp',
    'server',
    'user-plus',
    'user-times',
    'bed',
    'viacoin',
    'train',
    'subway',
    'medium',
    'y-combinator',
    'optin-monster',
    'opencart',
    'expeditedssl',
    'battery-full',
    'battery-three-quarters',
    'battery-half',
    'battery-quarter',
    'battery-empty',
    'mouse-pointer',
    'i-cursor',
    'object-group',
    'object-ungroup',
    'sticky-note',
    'sticky-note-o',
    'cc-jcb',
    'cc-diners-club',
    'clone',
    'balance-scale',
    'hourglass-o',
    'hourglass-start',
    'hourglass-half',
    'hourglass-end',
    'hourglass',
    'hand-rock-o',
    'hand-paper-o',
    'hand-scissors-o',
    'hand-lizard-o',
    'hand-spock-o',
    'hand-pointer-o',
    'hand-peace-o',
    'trademark',
    'registered',
    'creative-commons',
    'gg',
    'gg-circle',
    'tripadvisor',
    'odnoklassniki',
    'odnoklassniki-square',
    'get-pocket',
    'wikipedia-w',
    'safari',
    'chrome',
    'firefox',
    'opera',
    'internet-explorer',
    'television',
    'contao',
    '500px',
    'amazon',
    'calendar-plus-o',
    'calendar-minus-o',
    'calendar-times-o',
    'calendar-check-o',
    'industry',
    'map-pin',
    'map-signs',
    'map-o',
    'map',
    'commenting',
    'commenting-o',
    'houzz',
    'vimeo',
    'black-tie',
    'fonticons'
  ];

  constructor(private typeService: TypeService, private categoryService: CategoryService) {
    this.basicForm = new FormGroup({
      name: new FormControl('', Validators.required),
      label: new FormControl('', Validators.required),
      description: new FormControl(''),
      active: new FormControl(true)
    });
    this.basicMetaIconForm = new FormGroup({
      icon: new FormControl('fa-cube'),
    });
    this.basicCategoryForm = new FormGroup({
      category_id: new FormControl(null)
    });
  }

  public get name() {
    return this.basicForm.get('name');
  }

  public get label() {
    return this.basicForm.get('label');
  }

  public ngOnInit(): void {
    if (this.mode === CmdbMode.Create) {
      this.basicForm.get('name').setAsyncValidators(TypeNameValidator.createValidator(this.typeService));
      this.basicForm.get('label').valueChanges.subscribe(val => {
        this.basicForm.get('name').setValue(val.toString().charAt(0).toLowerCase() + val.toString().slice(1));
        this.basicForm.get('name').markAsDirty({onlySelf: true});
        this.basicForm.get('name').markAsTouched({onlySelf: true});
      });
      this.basicCategoryForm.get('category_id').setValidators(Validators.required);
    } else if (this.mode === CmdbMode.Edit) {
      this.basicForm.markAllAsTouched();
    }
    this.categoryList = this.categoryService.getCategoryList();
  }

}
