sudo: false

language: python

python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6

env:
    - DATBASE_HOST=127.0.0.1 DATBASE_POST=27017

services:
    - mongodb

install:
    - pip install -r requirements-dev.txt

script:
    - pytest tests/
