sudo: false

language: python

python:
    - 3.4
    - 3.5
    - 3.6

services:
    - mongodb

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install --upgrade pip setuptools; fi
    - pip install -r requirements-dev.txt
