sudo: false

language: python

python:
    - 3.5
    - 3.6
    - "3.7-dev"

services:
    - mongodb

env:
    - TEST_HOST=127.0.0.1
    - TEST_PORT=27017
    - TEST_DATABASE=cmdb_test

install:
    - pip install -r requirements.txt
    - pip install .
script:
    - pytest tests
