[Database]
host = 127.0.0.1
port = 27017
database_name = cmdb

[WebServer]
host = 0.0.0.0
port = 4000

[OpenCelium]
host = 127.0.0.1
port = 9090
protocol = http
email = the_email
user = the_user
password = the_password