[Database]
host = 127.0.0.1
port = 27017
database_name = cmdb

[WebServer]
host = 0.0.0.0
port = 4000

[OpenCelium]
host = 4.145.88.82
port = 80
protocol = http
email = admin@opencelium.io
user = admin@opencelium.io
password = 1234