/*
* DATAGERRY - OpenSource Enterprise CMDB
* Copyright (C) 2026 becon GmbH
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <https://www.gnu.org/licenses/>.
*/
import { CmdbPort, PortSide } from './ports-overview.types';
/* ------------------------------------------------------------------------------------------------------------------ */

/**
 * What is being created, the first question of the creation assistant.
 *
 * It replaces a "side" field: a standard device gets plain ports, a patch panel gets equal numbers of
 * front and rear ports which the backend pairs by an internal connection.
 */
export enum PortDeviceKind {
    STANDARD = 'STANDARD',
    PATCH_PANEL = 'PATCH_PANEL'
}


/**
 * The naming half of a bulk request, and the whole body of the name preview.
 *
 * `syntax` names a standard device's ports and a panel's front face, `rear_syntax` the panel's rear
 * face. Names are generated by the backend from these keys - the frontend never builds one itself.
 */
export interface PortNamingRequest {
    device_kind: PortDeviceKind;
    syntax: string;
    rear_syntax?: string;
    count: number;
    start_index: number;
    prefix?: string;
    slot?: string;
}


/** Body of `POST /ports/object/<id>/bulk`: the naming keys plus the values shared by every port. */
export interface PortBulkRequest extends PortNamingRequest {
    status: number | null;
    port_type: number | null;
    speed: number | null;
    description: string | null;
}


/** Why a face's names cannot all be created: generated twice, or already taken on the object. */
export interface PortNameCollisions {
    duplicates: string[];
    existing: string[];
}


/** One face of the device: a standard device has one, a panel has front and rear. */
export interface PortPreviewFace {
    side: PortSide;
    names: string[];
    collisions: PortNameCollisions;
}


/** Which front name the backend will pair with which rear name. Patch panels only. */
export interface PortPreviewPair {
    front: string;
    rear: string;
}


/** Answer of `POST /ports/object/<id>/name_preview`. */
export interface PortNamePreview {
    faces: PortPreviewFace[];
    pairs?: PortPreviewPair[];
    total: number;
}


/** Answer of the bulk creation. `connections` holds a panel's internal pairing. */
export interface PortBulkResult {
    ports: CmdbPort[];
    connections: unknown[];
    total_ports: number;
    total_connections: number;
}
