version: "3.0"
services:
  nginx:
    image: becongmbh/nginx:latest
    hostname: nginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - datagerry
    environment:
      NGINX_SSL_CERT: "/data/cert/cert.pem"
      NGINX_SSL_KEY: "/data/cert/key.pem"
      NGINX_LOCATION_DEFAULT: "/;/;http://datagerry:4000"
    restart: unless-stopped
    volumes:
      - ./cert:/data/cert

  datagerry:
    image: becongmbh/datagerry:latest
    hostname: datagerry
    depends_on:
    - db
    environment:
      DATAGERRY_Database_host: "db"
    restart: unless-stopped

  db:
    image: mongo:4.4.29
    hostname: db
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:
