version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/app"
    update_schedule: "live"
    target_branch: "development"
    commit_message:
      prefix: "[dep][js]"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "development"
    commit_message:
      prefix: "[dep][py]"
