// option-type.enum.ts

export enum OptionType {
    OBJECT_GROUP = 'OBJECT_GROUP',
    THREAT = 'THREAT',
    VULNERABILITY = 'VULNERABILITY',
    RISK = 'RISK',
    CONTROL_MEASURE = 'CONTROL_MEASURE',
    THREAT_VULNERABILITY = 'THREAT_VULNERABILITY',
  }
  