version: "3.0"
services:
  datagerry:
    image: nethinks/datagerry:latest
    ports:
    - "4000:4000"
    depends_on:
    - db
    - broker
    environment:
      DATAGERRY_Database_host: "db"
      DATAGERRY_MessageQueueing_host: "broker"
    restart: unless-stopped

  db:
    image: mongo:4.2-bionic
    
  broker:
    image: rabbitmq:3.8
